# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LQGxMWXAnDN70u7NGisn6E1ugRwg2SqC
"""
import sys
import tracemalloc

import time
start_time = time.time()
import csv

import numpy as np

import psutil

tracemalloc.start()
gap=30
def corres(x):
  if x=='A':
    return 0
  if x=='C':
    return 1
  if x=='G':
    return 2
  if x=='T':
    return 3
def mismatch(str1,str2,len1,len2,match,align):
  gap=30
  for i in range(1,len1+2):
    l1=corres(str1[i-1])
    
    for j in range(1,len2+2):
      l2=corres(str2[j-1])
      
      match[i,j]=min(align[l1][l2]+match[i-1][j-1],gap+match[i-1][j],gap+match[i][j-1])
  print(match)
  return match
def output(match2,align,len1,len2,str1,str2):
  i=int(len1)
  j=int(len2)
  max=i+j
  x1=[]
  x2=[]
  print(match2.shape)
  while i!=0 and j!=0:
    l1=corres(str1[i-1])
    l2=corres(str2[j-1])
    
   
    if match2[i][j] == (align[l1][l2]+match2[i-1][j-1]):
      x1.append(str1[i-1])
      x2.append(str2[j-1])
      i-=1
      j-=1
    
   
    elif match2[i][j]==(gap+match2[i][j-1]):
      x1.append('_')
      x2.append(str2[j-1])
      j-=1
    elif match2[i][j]==(gap+match2[i-1][j]):
      x1.append(str1[i-1])
      x2.append('_')
      i-=1
    
    
    
    
  print(len(x1))  
  print(x2)
  while(i!=0):
      if i>=0:
        x1.append(str1[i-1])
        i-=1
      
        x2.append('_')
  while(j!=0):
      if j>=0:
        x2.append(str2[j-1])
        j-=1
      
        x1.append('_')
  
  x1.reverse()
  x2.reverse()
  x11=''.join(x1)
  x22=''.join(x2)
  s1=x11[:50]+' '+x11[-50:]
  s2=x22[:50]+' '+x22[-50:]
  
  textout(s1,s2,match2[int(len1)][int(len2)])
def textout(s1,s2,cost):
  f=open("output.txt","w")
    
  f.write(str(s1)+"\n")
  f.write(str(s2)+"\n")
  f.write(str(cost)+"\n")
  
  f.write(str(tracemalloc.get_traced_memory()[1] / (1024 ))+"\n")
  f.write(str(time.time() - start_time)+"\n")
  tracemalloc.stop()
  
trainimg=[]
with open(str(sys.argv[1])) as csvfile:
    reader = csv.reader(csvfile) # change contents to floats
    for row in reader: # each row is a list
        
        trainimg.append(row[0])
print(trainimg)
str1=trainimg[0]
for i in range (1,len(trainimg)):
  l=str(trainimg[i])
  
  if str(trainimg[i]).isnumeric():
    str1=str1[:int(l)+1]+str1+str1[int(l)+1:len(str1)]
    
  else:
    break
str2=trainimg[i]
for k in range (i,len(trainimg)):
  l=str(trainimg[k])
  
  if str(trainimg[k]).isnumeric():
    str2=str2[:int(l)+1]+str2+str2[int(l)+1:len(str2)+1]
    
align=np.zeros((4,4))
match=np.zeros((len(str1)+1,len(str2)+1))

for i in range(len(str1)+1):
  match[i][0]=i*gap
for i in range(len(str2)+1):
  match[0][i]=i*gap

align[0][0]=0
align[0][1]=110
align[0][2]=48
align[0][3]=94
align[1][2]=118
align[1][3]=48
align[2][3]=110
align=align+align.T


print()
x=mismatch(str1,str2,len(str1)-1,len(str2)-1,match,align)

output(x,align,len(str1),len(str2),str1,str2)